### ISSUE TITLE
Add support for custom pillars

### ISSUE THREAD

**Issue by boformer** [earalov/Skylines-NoPillars#1]
MrMaison is working on custom pillars for his NYC elevated station (The default side pillars are not suitable for 9m high train tracks above roads).

This mod should just search for custom pillars (e.g. detecting an extra xml file in the asset directory) and make them selectable (for now just by clicking on the button).

Later it would make sense to have a separate window to select the pillar (only shown when elevated/bridge mode is enabled).

I created this script to unlock the default pillar in the asset editor: 

``` c#
PrefabCollection<BuildingInfo>.FindLoaded("RailwayElevatedPillar").m_AssetEditorTemplate = true;
```

The pillar uses a simple "BuildingAI" and can be found in the public transport category in the asset editor.

**Comment by boformer** [comment]
I created this mod for custom pillar support: http://steamcommunity.com/sharedfiles/filedetails/?id=543722850

**Comment by bloodypenguin** [comment]
I wonder why you published that instead of contributing to this mod. It's generally not a good practice to make mods with overlapping functionality.

**Comment by boformer** [comment]
I want to add more features in the future, like I mentioned in the description. I want all features to be purely visual, unlike the "Overlap" and "No zoning" function of No pillars.

I will publish the source soon, but first I'm working on a good way to organize the GUI (different tabs for ground, elevated and bridge+ only display relevant tabs/options).

Do you know how the auto layout feature of the GUI works?
